- hosts: db
  sudo: true
  tasks:
    - name: installs mariadb
      yum:
        name: mariadb-server, mariadb
        state: latest
    - name: starts mariadb
      service: 
        name: mariadb
        state: started
        enabled: true
    - name: restarts mariadb
      service:
        name: mariadb
        state: restarted