- hosts: dhcp
  sudo: true
  tasks:
      - name: install kea and mariadb
        yum:
            name: kea, mariadb, mariadb-server
            state: present
      - name: start db
        service:
            name: mariadb
            state: started
            enabled: true
      - name: copy config
        copy:
            src: kea.conf
            dest: /etc/kea/kea.conf
      - name: start kea
        service:
            name: kea-dhcp4
            state: started
            enabled: true