- hosts: all
  sudo: true
  vars:
  - pdns_config:
      master: true
      slave: false
      local-address: '192.168.121.2'
  - pdns_backends:
      gmysql:
        host: 192.168.121.3
        port: 3306
        user: powerdns
        password: passwd
        dbname: pdns
  - pdns_mysql_databases_credentials:
      gmysql:
        priv_user: root
        priv_password: root
        priv_host:
          - "%"
  - pdns_install_repo: "{{ pdns_auth_powerdns_repo_41 }}"
